### PR TITLE
Issue #94: Fix configuration file deployment path for agent 6 checks

### PR DESCRIPTION
**Pull request by DownRangeDevOps**
* Agent 6 stores conf files for checks in /etc/datadog-agent/conf.d/<integration>.d/conf.yaml
* Agent 5 stores conf files for checks in /etc/datadog-agent/conf.d/<integration>.yaml

https://github.com/DataDog/ansible-datadog/issues/94

### CODE REVIEW

**Comment by callumj** [comment]
Any chance on this being merged in? This fix seems critical to the DD agent functioning correctly for custom checks under v6.

**Comment by olivielpeau** [comment]
Just to clarify, the Agent v6 reads a check's configuration from both:
* the `/etc/datadog-agent/conf.d/<check_name>.d/<anything>.yaml` files, and
* the `/etc/datadog-agent/conf.d/<check_name>.yaml` file

so this change is not strictly required for the Agent v6 to work as expected, even though we do encourage the `/etc/datadog-agent/conf.d/<check_name>.d/` pattern in Agent 6 now.

@callumj if you're having trouble making a custom check work with Agent 6, can you double-check if the changes on the embedded python environment on Agent6 could affect you custom check? See https://github.com/DataDog/datadog-agent/blob/54ae03a64abba52e0e0b3cf057754589fb335633/docs/agent/changes.md#python-modules. Feel free to contact our support team and send a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) for help troubleshooting!

**Comment by lattwood** [comment]
This is going to need to ensure those directories exist before placing the files there. (See DataDog/ansible-datadog#109 )

**Comment by hush-hush** [comment]
Thank @techFishIO  for the PR, I'm closing it since it's a duplicate from #102.

**Pull request closed without merging**
