### PR TITLE
Add a note about installing marketplace integrations. Fixes #344

### LINKED ISSUE #344: Compatibility with installing Marketplace integrations via Ansible role
I was wondering if there were plans to allow Marketplace integrations to be installed via the ansible role?

### PR DESCRIPTION
**Pull request by bkabrda**

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by albertvaka** [comment]
There was a section already that mentioned `third_party: true` in the README, but it didn't mention marketplace so it wasn't that great. Maybe we can remove that section now?

**Comment by bkabrda** [comment]
@albertvaka the only mention of third party in the README is just below, in the syntax section, which just says `To install third party integrations, set third_party to true:` with an example. Since marketplace integrations are not the only kind of third party integrations, I think it makes sense to just add a section like this. WDYT?

**Comment by albertvaka** [comment]
👍

**Review by albertvaka — APPROVED** [review]

**Review by apigirl — APPROVED** [review]
docs look good 👍

**Pull request merged**
